### ISSUE TITLE
Possibilidade de haver mais de um telefone/documento por visitante?

### ISSUE THREAD

**Issue by otaviogaiao** [otaviogaiao/controle-visitantes#20]
No momento, o formulário de criação de visitante apenas permite adicionar um telefone e um documento. Isso está correto? O certo não seria permitir mais? Talvez trabalhar com minimo de 1 e máximo de 3?

**Comment by jcserracampos** [comment]
Desde o princípio é para permitir, só que tem que fazer o nested dinâmico.
Utilizar jQuery para isso.

**Comment by otaviogaiao** [comment]
Nested implementado. Utilizada uma gem do rails para isso.
