### ISSUE TITLE
local_visitado não foi definido ainda.

### ISSUE THREAD

**Issue by otaviogaiao** [otaviogaiao/controle-visitantes#8]
Atualmente local_visitado_id na tabela visitas não está sendo usado. Originalmente ela deveria ser uma foreign key para uma tabela de lotações. Deve-se definir o que vai ser feito sobre essa funcionalidade.

**Comment by jcserracampos** [comment]
Nesta versão, migrar para string.
Pensei em uma tabela com os locais cadastrados por um administrador, mas precisaríamos de uma tela de administração.

**Comment by otaviogaiao** [comment]
scaffold para locais já foi criado.
